### PR TITLE
Edit manuscript

### PR DESCRIPTION
**Pull request by stephendl102**

### CODE REVIEW

**Comment by stephendl102** [comment]
@aarmey @cyrillustan So, I'm realizing that a test for testMix is causing my pull requests to fail. Do either of you know how to fix it? I gave it a try in my last commit, so that might need to be undone.

**Comment by aarmey** [comment]
This has been intermittently failing for a while, I believe. @cyrillustan is probably best equipped to fix.

**Comment by cyrillustan** [comment]
You can just mute the testMixture if that is the case.

**Comment by stephendl102** [comment]
@cyrillustan Ok, I did that. Now dataFrames is not working?

**Comment by stephendl102** [comment]
@aarmey Is there anything I need to do to make codecov pass?

**Comment by aarmey** [comment]
Nope. Ignore it.

**Pull request merged**
