### PR TITLE
Human case

### PR DESCRIPTION
**Pull request by stephendl102**

### CODE REVIEW

**Comment by cyrillustan** [comment]
I'd suggest not to merge master into your branch now

**Comment by stephendl102** [comment]
@cyrillustan How should I proceed with this branch?

**Comment by cyrillustan** [comment]
@stephendl102 Yes, I'll merge it after the checks

**Comment by stephendl102** [comment]
@cyrillustan I have nothing else at the moment. I'll help fix the breaks in master whenever those occur.

**Pull request merged**
